#!/usr/bin/env bash

# Copyright (c) Robert LaRocca, http://www.laroccx.com

## Uncomment to install into the ~/ directory.
# mv -v $HOME/.ash_aliases $HOME/.ash_aliases-bak
# cp -v $PWD/ash_aliases.sh $HOME/.ash_aliases && chmod 0600 $HOME/.ash_aliases*
# touch $HOME/.ash_private && chmod 0600 $HOME/.ash_private*

## Uncomment to install into the ~/ directory.
mv -v $HOME/.bash_aliases $HOME/.bash_aliases-bak
cp -v $PWD/bash_aliases.sh $HOME/.bash_aliases && chmod 0600 $HOME/.bash_aliases*
touch $HOME/.bash_private && chmod 0600 $HOME/.bash_private*

## Uncomment to install into the ~/ directory.
mv -v $HOME/.zsh_aliases $HOME/.zsh_aliases-bak
cp -v $PWD/zsh_aliases.sh $HOME/.zsh_aliases && chmod 0600 $HOME/.zsh_aliases*
touch $HOME/.zsh_private && chmod 0600 $HOME/.zsh_private*

## Uncomment to install into the /root directory.
# sudo mv -v /root/.ash_aliases /root/.ash_aliases-bak
# sudo cp -v $PWD/ash_aliases.sh /root/.ash_aliases && sudo chmod 0600 /root/.ash_aliases*
# sudo touch /root/.ash_private && sudo chmod 0600 /root/.ash_private*

## Uncomment to install into the /root directory.
sudo mv -v /root/.bash_aliases /root/.bash_aliases-bak
sudo cp -v $PWD/bash_aliases.sh /root/.bash_aliases && sudo chmod 0600 /root/.bash_aliases*
sudo touch /root/.bash_private && sudo chmod 0600 /root/.bash_private*

## Uncomment to install into the /root directory.
sudo mv -v /root/.zsh_aliases /root/.zsh_aliases-bak
sudo cp -v $PWD/zsh_aliases.sh /root/.zsh_aliases && sudo chmod 0600 /root/.zsh_aliases*
sudo touch /root/.zsh_private && sudo chmod 0600 /root/.zsh_private*

## Uncomment to install into the /etc/skel directory.
# sudo cp -v $PWD/ash_aliases.sh /etc/skel/.ash_aliases && sudo chmod 0600 /etc/skel/.ash_aliases*
# sudo touch /etc/skel/.ash_private && sudo chmod 0600 /etc/skel/.ash_private*

## Uncomment to install into the /etc/skel directory.
# sudo cp -v $PWD/bash_aliases.sh /etc/skel/.bash_aliases && sudo chmod 0600 /etc/skel/.bash_aliases*
# sudo touch /etc/skel/.bash_private && sudo chmod 0600 /etc/skel/.bash_private*

## Uncomment to install into the /etc/skel directory.
# sudo cp -v $PWD/zsh_aliases.sh /etc/skel/.zsh_aliases && sudo chmod 0600 /etc/skel/.zsh_aliases*
# sudo touch /etc/skel/.zsh_private && sudo chmod 0600 /etc/skel/.zsh_private*

## Uncomment to install into the /usr/local/bin directory.
# sudo cp -v $PWD/caffeinate.sh /usr/local/bin/caffeinate && sudo chmod 0755 /usr/local/bin/caffeinate
# sudo cp -v $PWD/theme-helper.sh /usr/local/bin/theme-helper && sudo chmod 0755 /usr/local/bin/theme-helper
sudo cp -v $PWD/clean.py /usr/local/bin/clean && sudo chmod 0755 /usr/local/bin/clean
sudo cp -v $PWD/git-sync.sh /usr/local/bin/git-sync && sudo chmod 0755 /usr/local/bin/git-sync
sudo cp -v $PWD/swupdate.sh /usr/local/bin/swupdate && sudo chmod 0755 /usr/local/bin/swupdate
sudo cp -v $PWD/whatsmyip.py /usr/local/bin/whatsmyip && sudo chmod 0755 /usr/local/bin/whatsmyip

# vi: syntax=sh ts=2 noexpandtab
