#!/bin/bash

# Copyright (c) 2023 Robert LaRocca http://www.laroccx.com

# Install into the current user home.
touch $HOME/.bash_private
cp -b -S .bak -v $PWD/bash_aliases.sh $HOME/.bash_aliases
chmod 0640 $HOME/.bash_aliases

# Uncomment to enable install into the root home.
# sudo touch /root/.bash_private
# sudo cp -b -S .bak -v $PWD/bash_aliases.sh /root/.bash_aliases
# sudo chmod 0640 /root/.bash_aliases

# Uncomment to enable install into the /etc/skel directory.
# sudo touch /etc/skel/.bash_private
# sudo cp -b -S .bak -v $PWD/bash_aliases.sh /etc/skel/.bash_aliases
# sudo chmod 0644 /etc/skel/.bash_aliases

sudo cp -b -S .bak -v $PWD/caffeinate.sh /usr/local/bin/caffeinate
sudo chown root:root /usr/local/bin/caffeinate
sudo chmod 0755 /usr/local/bin/caffeinate

sudo cp -b -S .bak -v $PWD/git-sync.sh /usr/local/bin/git-sync
sudo chown root:root /usr/local/bin/git-sync
sudo chmod 0755 /usr/local/bin/git-sync

sudo cp -b -S .bak -v $PWD/swupdate.sh /usr/local/bin/swupdate
sudo chown root:root /usr/local/bin/swupdate
sudo chmod 0755 /usr/local/bin/swupdate

sudo cp -b -S .bak -v $PWD/theme-helper.sh /usr/local/bin/theme-helper
sudo chown root:root /usr/local/bin/theme-helper
sudo chmod 0755 /usr/local/bin/theme-helper

sudo cp -b -S .bak -v $PWD/whatsmyip.sh /usr/local/bin/whatsmyip
sudo chown root:root /usr/local/bin/whatsmyip
sudo chmod 0755 /usr/local/bin/whatsmyip

# vi: syntax=sh ts=2 noexpandtab
